# Generated by Django 4.2.7 on 2023-11-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DummyGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DummyGame', max_length=100, unique=True)),
                ('description', models.CharField(default='', max_length=2000)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
    ]
