# Generated by Django 4.2.7 on 2023-12-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Această migrație creează modelul Game în baza de date.
    """

    initial = True

    dependencies = [
        # Lista de migrări de care depinde această migrație
        # (în acest caz, nu depinde de nicio migrație anterioară)
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            # Definirea câmpurilor modelului
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DefaultName', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('developer', models.CharField(blank=True, max_length=255, null=True)),
                ('ram_min', models.FloatField(blank=True, null=True)),
                ('cpu_min', models.CharField(blank=True, max_length=255, null=True)),
                ('gpu_min', models.CharField(blank=True, max_length=255, null=True)),
                ('OS_min', models.CharField(blank=True, max_length=255, null=True)),
                ('storage_min', models.FloatField(blank=True, null=True)),
                ('ram_rec', models.FloatField(blank=True, null=True)),
                ('cpu_rec', models.CharField(blank=True, max_length=255, null=True)),
                ('gpu_rec', models.CharField(blank=True, max_length=255, null=True)),
                ('OS_rec', models.CharField(blank=True, max_length=255, null=True)),
                ('storage_rec', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
