# Generated by Django 4.2.7 on 2023-11-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.JSONField()),
                ('minimum_requirements', models.JSONField()),
                ('recommended_requirements', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('developer', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MinimumRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OS_min', models.CharField(max_length=255)),
                ('cpu_min', models.CharField(max_length=255)),
                ('gpu_min', models.CharField(max_length=255)),
                ('ram_min', models.IntegerField()),
                ('storage_min', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OS_rec', models.CharField(blank=True, max_length=255, null=True)),
                ('cpu_rec', models.CharField(blank=True, max_length=255, null=True)),
                ('gpu_rec', models.CharField(blank=True, max_length=255, null=True)),
                ('ram_rec', models.IntegerField(blank=True, null=True)),
                ('storage_rec', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
