# Generated by Django 4.2.7 on 2023-12-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Această migrație modifică câteva câmpuri în modelul Game.
    """

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='OS_min',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='OS_rec',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='cpu_min',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='cpu_rec',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='gpu_min',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='gpu_rec',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='DefaultName', max_length=1500),
        ),
    ]
